apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: podinfo
spec:
  minReadySeconds: 5
  replicas: 2
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: gcr.io/certain-nexus-865/podinformation:latest
        ports:
        - containerPort: 80
