---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: podinfo
spec:
  minReadySeconds: 5
  replicas: 1
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: gcr.io/certain-nexus-865/podinformation:test
        ports:
        - containerPort: 8080
